server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://176.122.181.106:3306/Galaxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: qingren.7
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
        enabled: true
        max-file-size: 300MB
        max-request-size: 300MB

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.Galaxy

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
