server:
  port: 4396
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Galaxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: qingren.7
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
        enabled: true
        max-file-size: 300MB
        max-request-size: 300MB
  redis:
    host: localhost
    port: 6379
    database: 0


#type-aliases-package可以简化com.example.Galaxy.entity.Blog为Blog
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.Galaxy.entity

#pagehelper: shijishangzhezhong
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql


#MyBatis sql日志输出
logging:
  level:
    com.example.Galaxy: trace


